### ISSUE TITLE
InitialSyncError:  Error during initial loading

### ISSUE THREAD

**Issue by vlaguz** [muun/apollo#144]
Hello.
I'm trying to restore my wallet from the 12 words backup.
But I get the error:
Error during initial loading. Suggestion: Restart the application and try again.
Full log:

```
Error:ra.a: AssemblyStackTraceException:  Assembly trace:
at rx.Observable.flatMap[merge](Observable.java:3)
at rx.Observable.flatMap[merge](Observable.java:3)
at rx.Observable.timeout[timeout](Observable.java:8)
at nb.o.adapt[doOnNext](RxCallAdapterWrapper.java:15)
at mb.l0.R[flatMap](HoustonClient.java:3)
at rx.Observable.flatMap[merge](Observable.java:3)
at dc.t0.b[flatMap](OperationActions.java:4)
at rx.Observable.flatMap[merge](Observable.java:3)
at dc.t0.b[concatMap](OperationActions.java:6)
at dc.t0.b[takeLast](OperationActions.java:7)
at rx.Completable.andThen[delaySubscription](Completable.java:2)
at xc.g0.E[zip](SyncApplicationDataAction.kt:15)
at rx.Observable.concat[concatMap](Observable.java:2)
at xc.g0.E[takeLast](SyncApplicationDataAction.kt:17)
at xc.g0.E[doOnNext](SyncApplicationDataAction.kt:19)
at sb.e.i[subscribeOn](ExecutionTransformerFactory.java:2)
at rx.Observable.observeOn[observeOn](Observable.java:2)
Caused by: ra.a: HttpException:  HTTP 500 Internal Server Error
at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:5)
Caused by: ra.a: ServerFailureException:  We're facing a temporary issue. Please, try again later
at nb.o.m(RxCallAdapterWrapper.java:8)
at nb.l.call(Unknown Source:2)
at df.p.x(ObservableFn.java:1)
at df.e.call(Unknown Source:4)
at df.p.u(ObservableFn.java:3)
at df.k.call(Unknown Source:6)
Caused by: ra.a: InitialSyncError:  Error during initial loading. Suggestion: Restart the application and try again
at xc.g0.F(SyncApplicationDataAction.kt:6)
at xc.d0.call(Unknown Source:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:12)
at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:5)
at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:1)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:12)
at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:5)
at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:1)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:6)
at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:1)
at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:2)
at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:5)
at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:7)
at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:1)
at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:2)
at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:1)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Subscriber.setProducer(Subscriber.java:6)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Subscriber.setProducer(Subscriber.java:6)
at rx.Subscriber.setProducer(Subscriber.java:6)
at rx.Observable.subscribe(Observable.java:26)
at rx.Observable.subscribe(Observable.java:21)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Completable$30.onCompleted(Completable.java:1)
at rx.Completable$8.call(Completable.java:6)
at rx.Completable$8.call(Completable.java:1)
at rx.Completable.unsafeSubscribe(Completable.java:3)
at rx.Completable.unsafeSubscribe(Completable.java:12)
at rx.Completable.unsafeSubscribe(Completable.java:9)
at rx.Completable$32.call(Completable.java:2)
at rx.Completable$32.call(Completable.java:1)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Subscriber.setProducer(Subscriber.java:7)
at rx.Subscriber.setProducer(Subscriber.java:6)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Subscriber.setProducer(Subscriber.java:8)
at rx.Subscriber.setProducer(Subscriber.java:6)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at rx.Observable.unsafeSubscribe(Observable.java:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
```

What should I do?

**Comment by acrespo** [comment]
Hi there!

> What should I do?
For any kind of error while using the app you should definitely try contacting us to support@muun.com! We strive to offer top level support for our users. 

Having said that, the error looks like a problem with our server. That's usually a one-off and retrying normally succeeds, that's why the "restart app" suggestion. But if you are consistently seeing this error, please contact our support team and we'll be happy to help.

**Comment by acrespo** [comment]
I see that you have indeed contacted us and the issue has been solved. I'm glad we could be of help! I'll close this issue now.
